### ISSUE TITLE
Importing Variables & Mixins

### ISSUE THREAD

**Issue by ericclemmons** [cdonohue/css-modules-bootstrap#1]
In the event that a project creates it's _own_ `variables.less` (or other overrides), does it make sense for that to be the responsibility of the project's CSS?

``` css
@import "bootstrap/less/variables.less";

.button {
  composes: btn btn-success from 'bootstrap/less/buttons.less';
}
```

With a loader, there's not really a way of "getting in-between" the import and providing your own.

Is my assumption correct?
